# Configuración para Netlify
[build]
  command = "npm install && npm run build"
  publish = "dist/public"

[build.environment]
  NODE_ENV = "production"
  ADMIN_PASSWORD = "gawr2024"

[[functions]]
  name = "api"
  runtime = "nodejs18.x"

[dev]
  command = "npm run dev"
  port = 5000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200