# Configuración para Render.com
services:
  - type: web
    name: gawr-gura-whatsapp-bot
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ADMIN_PASSWORD
        value: gawr2024
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: auth-storage
      mountPath: /opt/render/project/src/auth_info
      sizeGB: 1